#!/usr/bin/env python
import argparse
import sys
import chemlab as cl
import os

import time

def view(args):
    from chemlab.io import datafile
    from chemlab.graphics import display_system, display_trajectory
    
    base, ext = os.path.splitext(args.filename)
    
    if not args.traj:
        df = datafile(args.filename)
        sys = df.read('system')
        display_system(sys)
    else:
        df = datafile(args.filename)
        sys = df.read('system')
        
        df = datafile(args.traj)
        times, frames = df.read('trajectory')
            
        display_trajectory(sys, times,  frames)
	
def plot(args):
    base, ext = os.path.splitext(args.filename)

parser = argparse.ArgumentParser()

subparsers = parser.add_subparsers()

# Contrib plugins
from chemlab.contrib import gromacs
gromacs.setup_commands(subparsers)

view_parser = subparsers.add_parser('view')
view_parser.add_argument('filename', type=str)
view_parser.add_argument('--traj', action='store', type=str)

view_parser.set_defaults(func=view)

args = parser.parse_args(sys.argv[1:])
args.func(args)